name: Vanilla Minecraft Server with Ngrok

on:
  workflow_dispatch:

jobs:
  run-minecraft:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok -y

    - name: Authenticate Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        ngrok config add-authtoken $NGROK_AUTH_TOKEN

    - name: Download and Prepare Vanilla Minecraft Server
      run: |
        mkdir -p server
        cd server
        echo "Downloading server jar..."
        curl -L -o server.jar https://launcher.mojang.com/v1/objects/0f67dd8cf618249ceadf5f1f5e5b0d52f2c020ec/server.jar

        echo "Waiting to ensure file is fully written..."
        sleep 5

        if [ ! -s server.jar ]; then
          echo "❌ Download failed or file is empty."
          exit 1
        fi

        echo "eula=true" > eula.txt

    - name: Start Minecraft Server and Ngrok Tunnel
      run: |
        cd server

        echo "Starting Minecraft server in background..."
        java -Xmx1G -Xms1G -jar server.jar nogui &
        sleep 30

        echo "Starting Ngrok TCP tunnel on port 25565..."
        ngrok tcp 25565 > ../ngrok.log &
        sleep 10

    - name: Get Ngrok Public Address
      run: |
        curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
        cat tunnels.json

    - name: Show Ngrok IP and Port
      run: |
        echo "Minecraft Server is online! Use this to connect:"
        addr=$(jq -r '.tunnels[0].public_url' < tunnels.json)
        echo "▶ Minecraft Address: $addr"
